#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL
#
# @type Quadrotor Wide
#
# @maintainer Julian Oes <julian@oes.ch>
#

. ${R}etc/init.d/rc.mc_defaults

set MIXER quad_w
param set MIS_DIST_1WP 16404.2
param set MIS_DIST_WPS 16404.2